services:
  nestjs-api:
    build:
      context: ./challenger-server
      target: production
    ports:
      - "8000:8000"
    env_file:
      - ./challenger-server/.env.production       
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend    
      target: runner 
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    restart: unless-stopped
    depends_on:
      - nestjs-api

  db:
    image: mysql:8    
    restart: always # Adicionado restart policy para garantir que o servi√ßo tente reiniciar
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: cartorio
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
     

volumes:
  mysql_data:
    driver: local
    
# docker-compose down
# docker system prune -a --force # Limpa imagens e caches antigos que podem estar corrompidos
# docker-compose up --build